language: c
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python-pip
    - curl
    - valgrind
    - autotools-dev
    - libexpat-dev
    - libmhash-dev
    - libpcre3-dev
    - libperl-dev
    - libssl-dev
    - libxslt1-dev
    - zlib1g-dev
    - gcc-4.8
install:
- pip install --user stormpath
script:
- CC=gcc-4.8 make -C test
env:
  global:
  - secure: eM0jQMFWqdS2s7MvdBqn9omkAmIrTq+WYQPorZ7ykwxz5A0ODuF/Mj+T9zXgADIjMFD0fOlwaPP03D3d6PBDr5U0pstLoqFgEysH5+3XgHUhGNU6ID8HU6bVA+NeDV0E2UPalvrHFZgDf4SxayKqhH6cxCROiUFpIzVoy70eual3XZu52334Ku2n8pOg+QLGOTRWdKzzYCb4Uy9xxuB92jeBVDuqad4ngR/F4IYggxKv6TOA0MzPCGOmRx0ZWdPyAvCaKP1eU1GmzGAyRREHPp1kzvBot2jSyL9Z7Udf28SVFrF374KSRbkZ7nbNdr7QHBqda1u5pl5Te0Kj2cM1/X3Msg81q84YhFlotfFSnUdlqSHG8AAsfmESFxcC/vrCWgNte8KIZ/JQ3piLzSURiMDXuafuv9m5Q6dd8iHRkcG59S47n3Ic7nhaA6ncDU0LDVxLNm0HfEkkCBnWfDaQkolhThgEWTSV9spAQOvL75QXeBkQZHsXvuFhW3y8T0xmct/UiI+bDZ74guVEW5R6Ei+nMfYKJ8D3/Xfd7FLBQnE3jDRcuNA28qPN2iDStiyYHi0yNJCkgj/rtazFVkcSKtmU09LDsmCp0rLfysoyjk/qw7aZTxa++M9P8Y4kLTis7JxNV5p6fIqzoYPQ+6k7ruTCYlAMXLEWaD/QqM8KFuA=
  - secure: LjOdC/WoRtJrkG/F4uGxZZQYPebC0iElzmnWvsG9opFeY8JlU34Lcxstf7cg/+SezrJQKCaaZuRKLDTYo0Vhe+TNI2/yoSuHwOiajBDoAsPKsoHsRqi91yNlbD6IxgNIrBOnBtsOPOWmsFlZP2K3x0Sry1UDwjdcHiGDkU1w5j27EYCQ9QLwc/ktOFz/KHwg632yOdlgb9ItrjjMdfcXjUKkCrORRAJWQHtPd4i8vTjssJNBieEsaJl2RCxC8YkfA7oqUEH+IcGrAPd3pOI5aRmPRM5KObS2VQ8zGM61drV2GQ+h3sHODYWJTy8GMGRuvTwzvqGwLUVYNTNLjDRMwxzWS6BBRWRNWJQZIPW3xPY+wkKl9PFpUmhldhMtyd0kCU9HxoeMcPftCyStks0e+J0l7UzESzrF0bpH9gwQ8pxaTDlpg1Jf7asi57CDhGXSzWNS1OHocyfXJ4Tvy5Dy9K/Xcat1Ba/TjrmU1pTiU+MYMMFa46lCDPR2VfhVDiT52GggoFmamChRZ0/7Tz5KNK7bjvRDIJ89sMwr4QIAEiB0P3GSP+kdVU5N1m3fs7NRYnUiLdIwO6fmzjxtVBPHOLfC/oD9nhwtFmQxb9UNoFb+ADBcUTUTVPRwcb5JZ5qgnsThtHGlzkggOSUQ2wgVcoUQIS8sQDPqZPPxmyYuw5M=
