language: c
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python-pip
    - curl
    - valgrind
    - autotools-dev
    - libexpat-dev
    - libmhash-dev
    - libpcre3-dev
    - libperl-dev
    - libssl-dev
    - libxslt1-dev
    - zlib1g-dev
    - gcc-4.8
install:
- pip install --user stormpath
script:
- CC=gcc-4.8 make -C test
env:
  - secure: G9E9qpTa8Ns3OcPbyCq4nWoooHIhT8/zaVbOTCdokfElhxaFmKGhaLNuuZDbrzzELISwYFgER3XeFZlbZnQH2rWlXawwGt5SlXKeljuD+nvzU3ncch3Jw34iLmYMBCoy93ehdsjFRTjC2cUSvESku4TqNnc3is2MQUc8dzVv1viFBjRYFewnSs3hLZIwqwqLF5dW6N43gNkF0zv4brOPGhYtThAmJKEyXVYtpV3Mo7uiVgp2oYQKmNPVJRNBJhjJ2pzD9TcfYRxqEPYQEHLyBGSYXqvU3bcSNKJLStwp5cuUt54U6H9JAvQ+pfjd7byxAd6PrAuKEfA05eLodHJ0edqUpcOFnUeMyphtOcUvgoxk1KndKlNQ9V0kYXMSnFs6b050M8UsaCBd7KdLSextFMLvVYP/HSKeGj3vM93ou1quF9dUWhPbEPvkMzcymC0R3M9/k3A87n8wdPtAXWj0uFxIrkh0/Ll4TRH8dxAj/VnpZx4Dywrk4SPH5ej5h9VwhQ/WXwAXyrVh4ADno6KbsFUY68UdDilhjHyr4ncURrs8cb2zJstcXXV4hA27Ok/ncr/SjYfOWvSwpMBzF1l5QeHq+5EIAm6qE3JbOZ8SnVNjYIU1g6vgXki5G0klKPKEB+btGtm4QdhqwPPkqY5m15GS+A6sOpKMlbaOf9HvrN0=
  - secure: Cij6XViBK4bPmtCuzFTg8QscsuypI2C5ZDjBDEgD802EzUbB4GRds3VBoZYvyyCHFDk1fQEy9QbkCgrBBnrtNpcGb1CtUZmBL6LVyH3IFhi4+cZ87QICeCmqEtk/N5b0lTBFQxFtnsSsPEn7LkYcLmwapv+LKWtZ4J+xkpihsGZTe389i7AMI90USxyc+1ZoQ0nsdNxYxPeg21JYvozQNRw5Z1zhVKQ0dZxkx9S6DEWp6oh5amhqHESskb0UlwQosa5IRrbUcZ1ZMPdxOgGQv9yHXLmaH7iXusCMmW0MlXKuhpdaQ/dIERFZm3DFycofIbmn0hJ4SvMdcP0FtN4FiCdFR38X9BexHOH5cpjfm2FWx0gBdYKVoiw4h9qXM4c0Hvv5pwoS+XXjs2GAjpzi3c/1Hx0L67NQL7zlaxAinJtX0t7PXN1siOdtMxSUBB1lNut63ukWEGOHXkNEH5M+M+BIsX963r4ZAJBzuX/PAQ3XZGOdhAQwfOtaUDec36fwDfNKNAWYVmuEXUpIrNhGwHvfSof2vYe8dySVARrbtChk8oZMsiV5sdW5N8eCpgoRQFGCI8YQcRvKuTPVySQMJHDV6Ke9OwLxjsJuMLRNpAmoUkqAcJXx44hLgBmu5SMgBnTtgFbifuOJ6MqjDMK9FOBTDXhFjmrqKTu7V0B7Jiw=
